#!/bin/bash
set -e

# === Input Arguments ===
FUNCTION_NAME=$1
GIT_REPO=$2
BRANCH=$3
JAVA_VERSION=$4
REGION=$5
ROLE_ARN=$6
SECRET_NAME=$7

echo "$(date) - Build started"
echo "FUNCTION_NAME = $FUNCTION_NAME"
echo "GIT_REPO      = $GIT_REPO"
echo "BRANCH        = $BRANCH"
echo "JAVA_VERSION  = $JAVA_VERSION"
echo "REGION        = $REGION"

# === Strip non-numeric prefix from JAVA_VERSION ===
# e.g. "java21" → "21", "spring17" → "17", "21" → "21"
JAVA_VERSION=$(echo "$JAVA_VERSION" | grep -oP '\d+' | head -1)

# === Gradle version matrix ===
# Lambda always uses Spring Boot 3.x → Gradle 8.10.2 is sufficient
# Spring Boot 4.x would need 8.14+ but Lambda never uses 4.x
if [[ "$JAVA_VERSION" -ge 21 ]]; then
  GRADLE_VERSION="8.10.2"
else
  GRADLE_VERSION="8.10.2"
fi

echo "GRADLE_VERSION = $GRADLE_VERSION"

# === Config ===
CLONE_DIR="/tmp/lambda-deploy-$FUNCTION_NAME"
RUNTIME="java${JAVA_VERSION}"
echo "Runtime: $RUNTIME"

# === Cleanup & Clone ===
rm -rf "$CLONE_DIR"
git clone -b "$BRANCH" "$GIT_REPO" "$CLONE_DIR" --depth=1
cd "$CLONE_DIR"

cleanup() {
  echo "Cleaning temporary files..."
  rm -rf "$CLONE_DIR"
}
trap cleanup EXIT

# === Generate Gradle wrapper if not present ===
# Repos generated by devninja don't include gradlew — generate it here
if [[ ! -f "./gradlew" ]]; then
  echo "gradlew not found — generating wrapper with Gradle ${GRADLE_VERSION}..."
  gradle wrapper --gradle-version "${GRADLE_VERSION}"
  echo "Gradle wrapper generated successfully"
fi
chmod +x ./gradlew

# === Build ===
echo "Building Lambda JAR..."
./gradlew shadowJar -x test --no-daemon

# === Locate JAR ===
FAT_JAR=$(find . -path "*/build/libs/*.jar" -not -name "*-plain.jar" \
  | xargs ls -S 2>/dev/null | head -n 1)

if [[ -z "$FAT_JAR" ]]; then
  echo "No JAR found in build/libs"
  ls -lh ./build/libs/ || true
  exit 1
fi
echo "JAR: $(basename "$FAT_JAR") ($(ls -lh "$FAT_JAR" | awk '{print $5}'))"

# === Detect Handler ===
HANDLER=$(unzip -l "$FAT_JAR" \
  | awk '{print $4}' \
  | grep 'LambdaHandler\.class$' \
  | head -n 1 \
  | sed 's|/|.|g; s|\.class$||')

if [[ -z "$HANDLER" ]]; then
  echo "LambdaHandler.class not found in JAR"
  exit 1
fi
echo "Handler: $HANDLER"

# === Deploy ===
echo "Deploying Lambda..."
if aws lambda get-function \
  --function-name "$FUNCTION_NAME" \
  --region "$REGION" >/dev/null 2>&1; then

  echo "Updating existing Lambda..."
  timeout 120 aws lambda update-function-code \
    --function-name "$FUNCTION_NAME" \
    --zip-file "fileb://$FAT_JAR" \
    --region "$REGION"

  echo "Waiting for code update to complete..."
  aws lambda wait function-updated-v2 \
    --function-name "$FUNCTION_NAME" \
    --region "$REGION"

  echo "Updating Lambda configuration..."
  aws lambda update-function-configuration \
    --function-name "$FUNCTION_NAME" \
    --region "$REGION" \
    --handler "$HANDLER" \
    --runtime "$RUNTIME" \
    --environment "Variables={AWS_SECRET_NAME=$SECRET_NAME}"

else
  echo "Creating new Lambda..."
  timeout 120 aws lambda create-function \
    --function-name "$FUNCTION_NAME" \
    --runtime "$RUNTIME" \
    --role "$ROLE_ARN" \
    --handler "$HANDLER" \
    --zip-file "fileb://$FAT_JAR" \
    --timeout 120 \
    --memory-size 512 \
    --region "$REGION" \
    --environment "Variables={AWS_SECRET_NAME=$SECRET_NAME}"
fi

echo "Waiting for Lambda to become active..."
aws lambda wait function-active-v2 \
  --function-name "$FUNCTION_NAME" \
  --region "$REGION"
sleep 15

# === Function URL ===
EXISTING_URL=$(aws lambda list-function-url-configs \
  --function-name "$FUNCTION_NAME" \
  --region "$REGION" \
  --query 'FunctionUrlConfigs[0].FunctionUrl' \
  --output text 2>/dev/null)

echo "Existing URL: $EXISTING_URL"

if [ -z "$EXISTING_URL" ] || [ "$EXISTING_URL" == "None" ] || [ "$EXISTING_URL" == "null" ]; then
  echo "Creating Function URL..."
  URL=$(aws lambda create-function-url-config \
    --function-name "$FUNCTION_NAME" \
    --auth-type NONE \
    --region "$REGION" \
    --query 'FunctionUrl' \
    --output text)
else
  echo "Function URL already exists"
  aws lambda update-function-url-config \
    --function-name "$FUNCTION_NAME" \
    --auth-type NONE \
    --region "$REGION" >/dev/null
  URL=$EXISTING_URL
fi

echo "Function URL: $URL"
echo "$(date) - END"
echo "Lambda deployment completed successfully!"