<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1" />
    <PackageReference Include="Moq" Version="4.20.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\hello-http-test\hello-http-test.csproj" />
  </ItemGroup>
</Project>
