logging.level.root=INFO
spring.datasource.hikari.data-source-properties.stringtype=unspecified
aws.secretsmanager.region=${AWS_REGION:us-east-1}
db.secret.name=${DB_SECRET_NAME:sb-lambda-testng-2/db}
spring.sql.init.mode=never
