micronaut:
  application:
    name: devninja-ai2dev-lambda

datasources:
  default:
    url: jdbc:postgresql://161.97.137.17:5432/admin_rails
    username: test_user_ps
    password: test_user454_ps
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES

logging:
  level:
    ROOT: INFO
    com.ai2dev: DEBUG
